-- Seed DmDungChung converted from docs/export.sql (Oracle old system).
-- Generated for QLTB SQL Server redesign.
-- Audit: MaNguoiNhap = 0044, TenNguoiNhap = Truong Van Voon.
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;

MERGE dbo.DmDungChung AS target
USING (VALUES
    (N'CHAT_LIEU', N'0001', N'Sắt', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 1),
    (N'CHAT_LIEU', N'0002', N'Gỗ', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 2),
    (N'CHAT_LIEU', N'0003', N'Da', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 3),
    (N'CHAT_LIEU', N'0004', N'Su', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 4),
    (N'CHAT_LIEU', N'0005', N'Nệm', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 5),
    (N'CHAT_LIEU', N'0006', N'Đá', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 6),
    (N'CHAT_LIEU', N'0007', N'Nhựa', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 7),
    (N'CHAT_LIEU', N'0008', N'Thủy tinh', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 8),
    (N'CHAT_LIEU', N'0009', N'Giấy', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 9),
    (N'CHAT_LIEU', N'0010', N'Nước', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: pthanh', 10),
    (N'CHAT_LIEU', N'0011', N'Khác', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: web', 11),
    (N'CHAT_LIEU', N'0012', N'Inox', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: 0043', 12),
    (N'CHAT_LIEU', N'0013', N'Thép không gỉ', N'Nguon: WTB_925_DM_CHAT_LIEU; Log user cu: 0564', 13),
    (N'CONG_VIEC_BTBD', N'0001', N'1', N'Nguon: WTB_910_DM_CONG_VIEC_BTBD; Log user cu: pthanh; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 1),
    (N'CONG_VIEC_BTBD', N'0002', N'2', N'Nguon: WTB_910_DM_CONG_VIEC_BTBD; Log user cu: pthanh; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 2),
    (N'CONG_VIEC_BTBD', N'0003', N'3', N'Nguon: WTB_910_DM_CONG_VIEC_BTBD; Log user cu: pthanh; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 3),
    (N'CONG_VIEC_BTBD', N'0004', N'4', N'Nguon: WTB_910_DM_CONG_VIEC_BTBD; Log user cu: pthanh; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 4),
    (N'CONG_VIEC_BTBD', N'0005', N'5', N'Nguon: WTB_910_DM_CONG_VIEC_BTBD; Log user cu: web; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 5),
    (N'DON_VI_CUNG_CAP', N'0001', N'Công ty MEC', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: pthanh', 1),
    (N'DON_VI_CUNG_CAP', N'0002', N'Công ty Phi Long', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: pthanh', 2),
    (N'DON_VI_CUNG_CAP', N'0003', N'Công ty Bách Khoa', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: pthanh', 3),
    (N'DON_VI_CUNG_CAP', N'0004', N'Công ty DWC', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: web', 4),
    (N'DON_VI_CUNG_CAP', N'0005', N'Thế giới di động', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Ghi chu cu: 1234; Log user cu: web', 6),
    (N'DON_VI_CUNG_CAP', N'0006', N'Hawaco', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: web', 7),
    (N'DON_VI_CUNG_CAP', N'0007', N'Điện Máy Xanh', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: 0563', 8),
    (N'DON_VI_CUNG_CAP', N'0008', N'Điện Máy Chợ Lớn', N'Nguon: WTB_911_DM_DON_VI_CUNG_CAP; Log user cu: 0563', 9),
    (N'DON_VI_TINH', N'0001', N'Bình', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 1),
    (N'DON_VI_TINH', N'0002', N'Bộ', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 2),
    (N'DON_VI_TINH', N'0003', N'Chai', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 3),
    (N'DON_VI_TINH', N'0004', N'Chiếc', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 4),
    (N'DON_VI_TINH', N'0005', N'Cuộn', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 5),
    (N'DON_VI_TINH', N'0006', N'Cái', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 6),
    (N'DON_VI_TINH', N'0007', N'Cây', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 7),
    (N'DON_VI_TINH', N'0008', N'Cục', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 8),
    (N'DON_VI_TINH', N'0009', N'Dây', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 9),
    (N'DON_VI_TINH', N'0010', N'Hệ thống', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 10),
    (N'DON_VI_TINH', N'0011', N'Hộp', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 11),
    (N'DON_VI_TINH', N'0012', N'Khối', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 12),
    (N'DON_VI_TINH', N'0013', N'Lọ', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 13),
    (N'DON_VI_TINH', N'0014', N'Viên', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 14),
    (N'DON_VI_TINH', N'0015', N'm3', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 15),
    (N'DON_VI_TINH', N'0016', N'm2', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: pthanh', 16),
    (N'DON_VI_TINH', N'0017', N'Lít', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: web', 17),
    (N'DON_VI_TINH', N'0018', N'm', N'Nguon: WTB_912_DM_DON_VI_TINH; Log user cu: 0563', 18),
    (N'KET_LUAN', N'0001', N'Hỏng', N'Nguon: WTB_913_DM_KET_LUAN; Log user cu: pthanh', 1),
    (N'KET_LUAN', N'0002', N'Không sử dụng', N'Nguon: WTB_913_DM_KET_LUAN; Log user cu: pthanh', 2),
    (N'KHO', N'0001', N'Kho Liêu', N'Nguon: WTB_914_DM_KHO; Log user cu: pthanh', 1),
    (N'KHO', N'0002', N'Kho Phước', N'Nguon: WTB_914_DM_KHO; Log user cu: pthanh', 2),
    (N'KHO', N'0003', N'Kho Hoà Cường', N'Nguon: WTB_914_DM_KHO; Log user cu: pthanh', 3),
    (N'LOAI_THANH_LY', N'0001', N'Hủy bỏ', N'Nguon: WTB_915_DM_LOAI_THANH_LY', NULL),
    (N'LOAI_THANH_LY', N'0002', N'Bán', N'Nguon: WTB_915_DM_LOAI_THANH_LY', NULL),
    (N'LY_DO_THANH_LY', N'0001', N'Hư hỏng', N'Nguon: WTB_928_DM_LY_DO_THANH_LY; Log user cu: pthanh', 1),
    (N'LY_DO_THANH_LY', N'0002', N'Không sử dụng', N'Nguon: WTB_928_DM_LY_DO_THANH_LY; Log user cu: pthanh', 1),
    (N'MAU_SAC', N'0001', N'Đỏ', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 1),
    (N'MAU_SAC', N'0002', N'Xanh lơ', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 2),
    (N'MAU_SAC', N'0003', N'Xanh đậm', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 3),
    (N'MAU_SAC', N'0004', N'Vàng', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 4),
    (N'MAU_SAC', N'0005', N'Đen', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 5),
    (N'MAU_SAC', N'0006', N'Xám', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 6),
    (N'MAU_SAC', N'0007', N'Trắng', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: pthanh', 7),
    (N'MAU_SAC', N'0008', N'Xanh lá cây', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: web', 8),
    (N'MAU_SAC', N'0009', N'Tím', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: web', 9),
    (N'MAU_SAC', N'0011', N'Hồng', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: web', 11),
    (N'MAU_SAC', N'0012', N'Trắng sữa', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: 0564', 12),
    (N'MAU_SAC', N'0013', N'Trắng sữa', N'Nguon: WTB_916_DM_MAU_SAC; Log user cu: 0563', 13),
    (N'NGUOI_PHU_TRACH', N'0001', N'Hồ Trung Nguyên', N'Nguon: WTB_929_DM_NGUOI_PHU_TRACH; Log user cu: pthanh; Thuoc bo phan: CNTT', 1),
    (N'NGUOI_PHU_TRACH', N'0002', N'Hoàng Bá Hải', N'Nguon: WTB_929_DM_NGUOI_PHU_TRACH; Log user cu: pthanh; Thuoc bo phan: CNTT', 2),
    (N'NGUOI_PHU_TRACH', N'0003', N'Nguyễn Văn Vinh', N'Nguon: WTB_929_DM_NGUOI_PHU_TRACH; Log user cu: pthanh; Thuoc bo phan: HCNS', 3),
    (N'NGUOI_PHU_TRACH', N'0004', N'Lê Thị Thu Thủy', N'Nguon: WTB_929_DM_NGUOI_PHU_TRACH; Log user cu: pthanh; Thuoc bo phan: TCKT', 4),
    (N'NGUOI_PHU_TRACH', N'0005', N'Huỳnh Thị Thu Thủy', N'Nguon: WTB_929_DM_NGUOI_PHU_TRACH; Log user cu: pthanh; Thuoc bo phan: TCKT', 5),
    (N'NHAN_HIEU', N'0053', N'Sony', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: web', 1),
    (N'NHAN_HIEU', N'0054', N'Maxell', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0043', 2),
    (N'NHAN_HIEU', N'0055', N'Yaskawa', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0043', 3),
    (N'NHAN_HIEU', N'0056', N'Jabra', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0043', 4),
    (N'NHAN_HIEU', N'0057', N'Draytex', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0043', 5),
    (N'NHAN_HIEU', N'0058', N'Electrolux', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0564', 6),
    (N'NHAN_HIEU', N'0059', N'Xiaomi', N'Nguon: WTB_917_DM_NHAN_HIEU; Log user cu: 0563', 7),
    (N'NHAN_HIEU', N'0001', N'HP', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0002', N'Toyota', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0003', N'Honda', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0004', N'Mitsubishi', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0005', N'Daikin', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0006', N'Casper', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0007', N'Brother', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0008', N'Epson', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0009', N'Xerox', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0010', N'Tally', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0011', N'Sharp', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0012', N'Toshiba', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0013', N'Sanaky', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0014', N'Sunhouse', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0015', N'OHAUS', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0016', N'Analytics', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0017', N'MilWaukee', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0018', N'HandyLab', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0019', N'Wildco', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0020', N'Testo', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0021', N'LQ', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0022', N'Nichipet', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0023', N'NESSLER50', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0024', N'Ricoh', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0025', N'Canon', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0026', N'Dell', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0027', N'Zibara', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0028', N'LG', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0029', N'Sanyo', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0030', N'Kangaroo', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0031', N'Hikvision', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0033', N'Panasonic', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0034', N'Samsung', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0035', N'Makita', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0036', N'Tân Cương', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0037', N'Homephone', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0038', N'Bosh', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0039', N'Funiki', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0040', N'Ebara', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0041', N'DAIKO', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0042', N'Xinda', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0043', N'Hach', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0044', N'Hanna', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0045', N'Siemens', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0046', N'Mitutoyo', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0047', N'ABB', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0048', N'Euromag', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0049', N'BMAG', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0050', N'Isomag', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0051', N'Oshima', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAN_HIEU', N'0052', N'Vsmart', N'Nguon: WTB_917_DM_NHAN_HIEU', NULL),
    (N'NHAT_KY_THIET_BI', N'0001', N'Phát sinh mới', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 1),
    (N'NHAT_KY_THIET_BI', N'0002', N'Sửa chữa', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 2),
    (N'NHAT_KY_THIET_BI', N'0003', N'Thay thế', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 3),
    (N'NHAT_KY_THIET_BI', N'0004', N'Luân chuyển', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 4),
    (N'NHAT_KY_THIET_BI', N'0005', N'Bảo trì', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 5),
    (N'NHAT_KY_THIET_BI', N'0006', N'Nhập kho', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 6),
    (N'NHAT_KY_THIET_BI', N'0007', N'Thanh lý', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 7),
    (N'NHAT_KY_THIET_BI', N'0008', N'Tái sử dụng', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 8),
    (N'NHAT_KY_THIET_BI', N'0009', N'Chuyển Tài sản --> Công cụ', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 9),
    (N'NHAT_KY_THIET_BI', N'0010', N'Chuyển Công cụ --> Tài sản', N'Nguon: WTB_918_DM_NHAT_KY_THIET_BI; Log user cu: pthanh', 10),
    (N'NHOM_DOI_TUONG', N'0001', N'Thiết bị Điện', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: pthanh; Ma nhom doi tuong: 0001; Ten nhom doi tuong: Thiết bị Điện', 1),
    (N'NHOM_DOI_TUONG', N'0002', N'Thiết bị Điện tử', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Ma nhom doi tuong: 0002; Ten nhom doi tuong: Thiết bị Điện tử', 2),
    (N'NHOM_DOI_TUONG', N'0003', N'Đồ vật, dụng cụ', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: pthanh; Ma nhom doi tuong: 0003; Ten nhom doi tuong: Đồ vật, dụng cụ', 3),
    (N'NHOM_DOI_TUONG', N'0004', N'Nhà cửa - Kiến trúc', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Ma nhom doi tuong: 0004; Ten nhom doi tuong: Nhà cửa - Kiến trúc', 4),
    (N'NHOM_DOI_TUONG', N'0005', N'Phương tiện Vận tải Ôtô', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: pthanh; Ma nhom doi tuong: 0005; Ten nhom doi tuong: Phương tiện Vận tải Ôtô', 5),
    (N'NHOM_DOI_TUONG', N'0006', N'Máy móc và thiết bị Thi công', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: pthanh; Ma nhom doi tuong: 0006; Ten nhom doi tuong: Máy móc và thiết bị Thi công', 6),
    (N'NHOM_DOI_TUONG', N'0007', N'Đồng hồ điện từ', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: pthanh; Ma nhom doi tuong: 0007; Ten nhom doi tuong: Đồng hồ điện từ', 7),
    (N'NHOM_DOI_TUONG', N'0008', N'Khác', N'Nguon: WTB_923_DM_NHOM_DOI_TUONG; Log user cu: web; Ma nhom doi tuong: 0008; Ten nhom doi tuong: Khác', 8),
    (N'NHOM_QUAN_LY', N'0001', N'Tài sản', N'Nguon: WTB_922_DM_NHOM_QUAN_LY; Log user cu: pthanh', 1),
    (N'NHOM_QUAN_LY', N'0002', N'Công cụ dung cụ', N'Nguon: WTB_922_DM_NHOM_QUAN_LY; Log user cu: pthanh', 2),
    (N'NUOC_SAN_XUAT', N'0001', N'Việt Nam', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 1),
    (N'NUOC_SAN_XUAT', N'0002', N'Đài Loan', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 2),
    (N'NUOC_SAN_XUAT', N'0003', N'Trung Quốc', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 3),
    (N'NUOC_SAN_XUAT', N'0004', N'Nhật Bản', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 4),
    (N'NUOC_SAN_XUAT', N'0005', N'Đức', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 5),
    (N'NUOC_SAN_XUAT', N'0006', N'Anh', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 6),
    (N'NUOC_SAN_XUAT', N'0007', N'Mỹ', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 7),
    (N'NUOC_SAN_XUAT', N'0008', N'Hàn Quốc', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 8),
    (N'NUOC_SAN_XUAT', N'0009', N'Thái Lan', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 9),
    (N'NUOC_SAN_XUAT', N'0010', N'Rumani', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 10),
    (N'NUOC_SAN_XUAT', N'0011', N'Ý', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: pthanh', 11),
    (N'NUOC_SAN_XUAT', N'0012', N'Nga', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: web', 12),
    (N'NUOC_SAN_XUAT', N'0013', N'Malaysia', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: web', 13),
    (N'NUOC_SAN_XUAT', N'0014', N'Pháp', N'Nguon: WTB_919_DM_NUOC_SAN_XUAT; Log user cu: web', 13),
    (N'TRANG_THAI_KK', N'0001', N'OK-Khớp', N'Nguon: WTB_926_DM_TRANG_THAI_KK; Ghi chu cu: ok; Log user cu: pthanh', 1),
    (N'TRANG_THAI_KK', N'0002', N'Dư thừa -> Thêm mới', N'Nguon: WTB_926_DM_TRANG_THAI_KK; Ghi chu cu: TB nằm ngoài DS đi KK; Log user cu: pthanh', 3),
    (N'TRANG_THAI_KK', N'0003', N'Thiếu - Mất', N'Nguon: WTB_926_DM_TRANG_THAI_KK; Ghi chu cu: Ko thấy TB khi KK; Log user cu: pthanh', 4),
    (N'TRANG_THAI_KK', N'0004', N'Điều chỉnh - Thay đổi', N'Nguon: WTB_926_DM_TRANG_THAI_KK; Ghi chu cu: Sửa thông số/linh kiện; Log user cu: pthanh', 5),
    (N'TRANG_THAI_KK', N'0005', N'Hư hỏng', N'Nguon: WTB_926_DM_TRANG_THAI_KK; Ghi chu cu: Hư hỏng; Log user cu: pthanh', 6),
    (N'TRANG_THAI_TB', N'0001', N'Đang hoạt động', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 1),
    (N'TRANG_THAI_TB', N'0002', N'Đang sửa chữa', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 2),
    (N'TRANG_THAI_TB', N'0003', N'Không sử dụng', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 3),
    (N'TRANG_THAI_TB', N'0004', N'Đã hỏng', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 4),
    (N'TRANG_THAI_TB', N'0005', N'Đã nhập kho', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 5),
    (N'TRANG_THAI_TB', N'0006', N'Đã thanh lý', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 6),
    (N'TRANG_THAI_TB', N'0007', N'Đang bảo trì', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: web', 7),
    (N'TRANG_THAI_TB', N'0008', N'Tạm ngừng hoạt động', N'Nguon: WTB_921_DM_TRANG_THAI_TB; Log user cu: pthanh', 8)
) AS source (NhomDanhMuc, Ma, Ten, GhiChu, SapXep)
ON target.NhomDanhMuc = source.NhomDanhMuc AND target.Ma = source.Ma
WHEN MATCHED THEN
    UPDATE SET
        target.Ten = source.Ten,
        target.GhiChu = source.GhiChu,
        target.SapXep = source.SapXep,
        target.IsActive = 1,
        target.NgayChinhSuaCuoiCung = SYSDATETIME(),
        target.MaNguoiChinhSua = N'0044',
        target.TenNguoiChinhSua = N'Trương Văn Voôn'
WHEN NOT MATCHED THEN
    INSERT (Id, NhomDanhMuc, Ma, Ten, GhiChu, SapXep, IsActive, NgayKhoiTao, MaNguoiNhap, TenNguoiNhap)
    VALUES (NEWID(), source.NhomDanhMuc, source.Ma, source.Ten, source.GhiChu, source.SapXep, 1, SYSDATETIME(), N'0044', N'Trương Văn Voôn');

COMMIT TRANSACTION;

SELECT NhomDanhMuc, COUNT(*) AS SoLuong
FROM dbo.DmDungChung
WHERE NhomDanhMuc IN (
    N'CHAT_LIEU',
    N'CONG_VIEC_BTBD',
    N'DON_VI_CUNG_CAP',
    N'DON_VI_TINH',
    N'KET_LUAN',
    N'KHO',
    N'LOAI_THANH_LY',
    N'LY_DO_THANH_LY',
    N'MAU_SAC',
    N'NGUOI_PHU_TRACH',
    N'NHAN_HIEU',
    N'NHAT_KY_THIET_BI',
    N'NHOM_DOI_TUONG',
    N'NHOM_QUAN_LY',
    N'NUOC_SAN_XUAT',
    N'TRANG_THAI_KK',
    N'TRANG_THAI_TB'
)
GROUP BY NhomDanhMuc
ORDER BY NhomDanhMuc;
