-- Thi?t k? CSDL Qu?n l� thi?t b? - SQL Server

CREATE TABLE dbo.DmDungChung (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    NhomDanhMuc NVARCHAR(50) NOT NULL,
    Ma NVARCHAR(50) NOT NULL,
    Ten NVARCHAR(250) NOT NULL,
    GhiChu NVARCHAR(500) NULL,
    SapXep INT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE UNIQUE INDEX IX_DmDungChung_Nhom_Ma
ON dbo.DmDungChung(NhomDanhMuc, Ma);
GO

CREATE TABLE dbo.DonViBoPhan (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MaDonVi NVARCHAR(50) NOT NULL,
    TenDonVi NVARCHAR(250) NOT NULL,
    ParentId UNIQUEIDENTIFIER NULL,
    LoaiDonVi NVARCHAR(50) NULL,
    GhiChu NVARCHAR(500) NULL,
    SapXep INT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE TABLE dbo.NguoiSuDungThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MaNguoiDung NVARCHAR(50) NOT NULL,
    TenNguoiDung NVARCHAR(250) NOT NULL,
    DonViBoPhanId UNIQUEIDENTIFIER NULL,
    ChucVu NVARCHAR(250) NULL,
    SoDienThoai NVARCHAR(50) NULL,
    Email NVARCHAR(250) NULL,
    GhiChu NVARCHAR(500) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE TABLE dbo.NhomThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MaNhomThietBi NVARCHAR(50) NOT NULL,
    TenNhomThietBi NVARCHAR(250) NOT NULL,
    KyHieu NVARCHAR(20) NULL,
    ParentId UNIQUEIDENTIFIER NULL,
    MoTa NVARCHAR(1000) NULL,
    SapXep INT NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE UNIQUE INDEX IX_NhomThietBi_Ma
ON dbo.NhomThietBi(MaNhomThietBi);
GO

CREATE TABLE dbo.ThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    MaThietBi NVARCHAR(50) NOT NULL,
    MaThietBiCu NVARCHAR(50) NULL,
    TenThietBi NVARCHAR(500) NOT NULL,
    SoSerial NVARCHAR(100) NULL,
    Model NVARCHAR(100) NULL,
    MaKeToan NVARCHAR(50) NULL,
    MaThietBiCha NVARCHAR(50) NULL,
    NhomThietBiId UNIQUEIDENTIFIER NOT NULL,
    TrangThaiId UNIQUEIDENTIFIER NOT NULL,
    TrangThaiKiemKeId UNIQUEIDENTIFIER NULL,
    DonViTinhId UNIQUEIDENTIFIER NULL,
    NhanHieuId UNIQUEIDENTIFIER NULL,
    MauSacId UNIQUEIDENTIFIER NULL,
    NuocSanXuatId UNIQUEIDENTIFIER NULL,
    ChatLieuId UNIQUEIDENTIFIER NULL,
    DonViCungCapId UNIQUEIDENTIFIER NULL,
    PhongBanId UNIQUEIDENTIFIER NULL,
    BoPhanId UNIQUEIDENTIFIER NULL,
    NguoiSuDungId UNIQUEIDENTIFIER NULL,
    NgayMua DATE NULL,
    NgayNhapThietBi DATE NULL,
    NgayDuaVaoSuDung DATE NULL,
    NguyenGia DECIMAL(18,2) NULL,
    ThoiGianBaoHanh INT NULL,
    NgayHetBaoHanh DATE NULL,
    MaQrCode NVARCHAR(100) NULL,
    ViTriLapDat NVARCHAR(500) NULL,
    GhiChu NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE UNIQUE INDEX IX_ThietBi_MaThietBi
ON dbo.ThietBi(MaThietBi);
GO

CREATE TABLE dbo.DmThongSoThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    NhomThietBiId UNIQUEIDENTIFIER NOT NULL,
    MaThongSo NVARCHAR(50) NOT NULL,
    TenThongSo NVARCHAR(250) NOT NULL,
    KieuDuLieu NVARCHAR(50) NOT NULL,
    DonViTinhId UNIQUEIDENTIFIER NULL,
    BatBuoc BIT NOT NULL DEFAULT 0,
    SapXep INT NULL,
    GhiChu NVARCHAR(500) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE UNIQUE INDEX IX_DmThongSoThietBi_Nhom_Ma
ON dbo.DmThongSoThietBi(NhomThietBiId, MaThongSo);
GO

CREATE TABLE dbo.ThietBiThongSo (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ThietBiId UNIQUEIDENTIFIER NOT NULL,
    ThongSoId UNIQUEIDENTIFIER NOT NULL,
    GiaTriText NVARCHAR(1000) NULL,
    GiaTriNumber DECIMAL(18,4) NULL,
    GiaTriDate DATE NULL,
    GiaTriBit BIT NULL,
    GhiChu NVARCHAR(500) NULL,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL
);
GO

CREATE UNIQUE INDEX IX_ThietBiThongSo_ThietBi_ThongSo
ON dbo.ThietBiThongSo(ThietBiId, ThongSoId);
GO

CREATE TABLE dbo.PhieuThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    SoPhieu NVARCHAR(50) NOT NULL,
    LoaiPhieu NVARCHAR(50) NOT NULL,
    NgayPhieu DATE NOT NULL,
    ThietBiId UNIQUEIDENTIFIER NOT NULL,
    PhongBanId UNIQUEIDENTIFIER NULL,
    BoPhanId UNIQUEIDENTIFIER NULL,
    NguoiSuDungId UNIQUEIDENTIFIER NULL,
    DonViThucHienId UNIQUEIDENTIFIER NULL,
    KetLuanId UNIQUEIDENTIFIER NULL,
    NoiDung NVARCHAR(1000) NULL,
    ChiPhi DECIMAL(18,2) NULL,
    FileScan01 NVARCHAR(500) NULL,
    FileScan02 NVARCHAR(500) NULL,
    GhiChu NVARCHAR(1000) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL,
    NgayChinhSuaCuoiCung DATETIME2 NULL,
    MaNguoiChinhSua NVARCHAR(50) NULL,
    TenNguoiChinhSua NVARCHAR(250) NULL
);
GO

CREATE TABLE dbo.PhieuThietBiChiTiet (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    PhieuThietBiId UNIQUEIDENTIFIER NOT NULL,
    CongViecId UNIQUEIDENTIFIER NULL,
    ThongSoId UNIQUEIDENTIFIER NULL,
    NoiDung NVARCHAR(1000) NULL,
    GiaTri NVARCHAR(1000) NULL,
    ChiPhi DECIMAL(18,2) NULL,
    NgayBatDau DATE NULL,
    NgayKetThuc DATE NULL,
    GhiChu NVARCHAR(500) NULL,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL
);
GO

CREATE TABLE dbo.LichSuThietBi (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    ThietBiId UNIQUEIDENTIFIER NOT NULL,
    LoaiNghiepVu NVARCHAR(50) NOT NULL,
    NghiepVuId UNIQUEIDENTIFIER NULL,
    TrangThaiTruocId UNIQUEIDENTIFIER NULL,
    TrangThaiSauId UNIQUEIDENTIFIER NULL,
    PhongBanTruocId UNIQUEIDENTIFIER NULL,
    PhongBanSauId UNIQUEIDENTIFIER NULL,
    BoPhanTruocId UNIQUEIDENTIFIER NULL,
    BoPhanSauId UNIQUEIDENTIFIER NULL,
    NguoiSuDungTruocId UNIQUEIDENTIFIER NULL,
    NguoiSuDungSauId UNIQUEIDENTIFIER NULL,
    NoiDung NVARCHAR(1000) NULL,
    NgayPhatSinh DATE NULL,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL
);
GO

CREATE TABLE dbo.TepDinhKem (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    DoiTuongLoai NVARCHAR(50) NOT NULL,
    DoiTuongId UNIQUEIDENTIFIER NOT NULL,
    TenFile NVARCHAR(500) NOT NULL,
    DuongDan NVARCHAR(1000) NOT NULL,
    LoaiFile NVARCHAR(50) NULL,
    DungLuong BIGINT NULL,
    GhiChu NVARCHAR(500) NULL,
    NgayKhoiTao DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    MaNguoiNhap NVARCHAR(50) NULL,
    TenNguoiNhap NVARCHAR(250) NULL
);
GO

-- Seed tr?ng th�i thi?t b? m?c d?nh
INSERT INTO dbo.DmDungChung (NhomDanhMuc, Ma, Ten, SapXep)
VALUES
(N'TRANG_THAI_TB', N'MOI_NHAP', N'M?i nh?p', 1),
(N'TRANG_THAI_TB', N'TRONG_KHO', N'Trong kho', 2),
(N'TRANG_THAI_TB', N'DANG_SU_DUNG', N'�ang s? d?ng', 3),
(N'TRANG_THAI_TB', N'DANG_SUA_CHUA', N'�ang s?a ch?a', 4),
(N'TRANG_THAI_TB', N'DANG_BAO_TRI', N'�ang b?o tr�/b?o du?ng', 5),
(N'TRANG_THAI_TB', N'CHO_THANH_LY', N'Ch? thanh l�', 6),
(N'TRANG_THAI_TB', N'DA_THANH_LY', N'�� thanh l�', 7),
(N'TRANG_THAI_TB', N'MAT_HUY', N'M?t/H?y', 8);
GO
